imports:
    - { resource: tables.yml }

services:
    spaceace.ajaxchat.listener:
        class: spaceace\ajaxchat\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '@config_text'
            - '@ext.manager'
            - '%core.php_ext%'
            - '%tables.ajax_chat%'
            - '@spaceace.ajaxchat.chat.controller'
        tags:
            - { name: event.listener }
    spaceace.ajaxchat.chat.controller:
        class: spaceace\ajaxchat\controller\chat
        arguments:
            - '@template'
            - '@template_context'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '@ext.manager'
            - '@path_helper'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.posts%'
            - '%tables.users%'
            - '%tables.ajax_chat%'
            - '%tables.ajax_chat_sessions%'
    spaceace.ajaxchat.cron.task.prune_ajaxchat:
        class: spaceace\ajaxchat\cron\task\prune_ajaxchat
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@log'
            - '%tables.ajax_chat%'
        calls:
            - [set_name, [cron.task.prune_ajaxchat]]
        tags:
            - { name: cron.task }
